question: |
  다음은 문서의 내용과 범주입니다.
  문서 범주: {category}
  문서 내용: {document}

  위 문서 내용과 범주를 바탕으로, 사용자가 궁금해할 만한 질문 {gen_num_questions}개를 생성해주세요. 각 질문은 줄바꿈으로 구분해주세요.

answer: |
  다음은 문서의 내용과 질문입니다.
  문서 내용: {document}
  질문: {question}

  위 문서 내용을 바탕으로 질문에 대해 상세하고 친절하게 답변해주세요.
  문서 내용과 질문의 내용을 반복하지 말고, 답변에 대해서만 간결하고 명쾌하게 대답해주세요.
