structural:
  _target_: src.datasets.SFTStructuralDataset
  data_path: ${connected_dir}/data
  split: ${split.train}
  split_ratio: ${split_ratio}
  is_strict_split: ${is_strict_split}
  seed: ${seed}
  dataset_name: ${dataset_name}
  dataset_format: ${dataset_format}
  is_sft: ${is_sft}
  is_preprocessed: ${is_preprocessed}
  instruction_column_name: ${instruction_column_name}
  data_column_name: ${data_column_name}
  target_column_name: ${target_column_name}
  role_column_name: ${role_column_name}
  content_column_name: ${content_column_name}
  assistant_column_name: ${assistant_column_name}
  pretrained_model_name: ${pretrained_model_name}
  custom_data_encoder_path: ${custom_data_encoder_path}
  revision: ${revision}
  reference_data_encoder_name: ${reference_data_encoder_name}
  left_padding: ${left_padding}
  is_enable_thinking: ${is_enable_thinking}
  max_length: ${max_length}
  response_start_template: ${response_start_template}

conversational:
  _target_: src.datasets.SFTConversationalDataset
  data_path: ${connected_dir}/data
  split: ${split.train}
  split_ratio: ${split_ratio}
  is_strict_split: ${is_strict_split}
  seed: ${seed}
  dataset_name: ${dataset_name}
  dataset_format: ${dataset_format}
  is_sft: ${is_sft}
  is_preprocessed: ${is_preprocessed}
  conversation_column_name: ${conversation_column_name}
  role_column_name: ${role_column_name}
  content_column_name: ${content_column_name}
  pretrained_model_name: ${pretrained_model_name}
  custom_data_encoder_path: ${custom_data_encoder_path}
  revision: ${revision}
  reference_data_encoder_name: ${reference_data_encoder_name}
  left_padding: ${left_padding}
  is_enable_thinking: ${is_enable_thinking}
  max_length: ${max_length}
  response_start_template: ${response_start_template}