# @package _global_
defaults:
  - prompt: prompt
  - hydra: hydra

package_name: synthetic-data-generator
project_dir: ${oc.env:PROJECT_DIR}/${package_name}
connected_dir: ${oc.env:CONNECTED_DIR}/${package_name}

seed: 2025

dataset_name: documents
data_dir: ${connected_dir}/data

document_column_name: 문서
category_column_name: 범주>카테고리>상품명>상품약관 파일명
gen_num_questions: 5
context_column_name: context
question_column_name: question
answer_column_name: answer

upload_user: Qwen
model_type: Qwen3-4B-Instruct-2507
pretrained_model_name: ${upload_user}/${model_type}
revision: main
reference_data_encoder_name: Qwen/Qwen3-4B-Instruct-2507
left_padding: true
is_enable_thinking: false

max_new_tokens: 2048
do_sample: true
generation_config:
  temperature: 0.6
  top_p: 0.95
  top_k: 20

model_name: Synthetic-QA
mode: generation

project_name: ${model_name}-${dataset_name}-${mode}

output_dir: ${connected_dir}/outputs/${dataset_name}/${model_type}
output_name: generated_eval_dataset

run_name: ${project_name}
work_dir: ${hydra:runtime.cwd}