# @package _global_
defaults:
  - hydra: hydra

package_name: synthetic-data-generator
project_dir: ${oc.env:PROJECT_DIR}/${package_name}
connected_dir: ${oc.env:CONNECTED_DIR}/${package_name}

seed: 2025

dataset_name: documents
dataset_format: csv
data_dir: ${connected_dir}/data
output_dir: ${connected_dir}/outputs/${dataset_name}/${model_type}
output_name: generated_eval_dataset

instruction_column_name: instruction
data_column_name: input
target_column_name: response
conversation_column_name: messages
role_column_name: role
content_column_name: content
assistant_column_name: assistant

upload_user: Qwen
model_type: Qwen3-30B-A3B-Instruct-2507
pretrained_model_name: ${upload_user}/${model_type}
revision: main
reference_data_encoder_name: Qwen/Qwen3-30B-A3B-Instruct-2507
left_padding: true
is_enable_thinking: false

model_name: Synthetic-QA
mode: generation

project_name: ${model_name}-${dataset_name}-${mode}

max_new_tokens: 512
do_sample: true
generation_config:
  temperature: 0.6
  top_p: 0.95
  top_k: 20

run_name: ${project_name}
work_dir: ${hydra:runtime.cwd}